import { describe, expect, it } from 'vitest';

import { makeFinding, makeResult, makeSummary } from './helpers.js';
import { generateExecutiveReport } from '../../src/reporting/executive.js';
import { Severity, Verdict } from '../../src/types/index.js';

describe('generateExecutiveReport', () => {
  it('includes executive summary header', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('# AI Agent Security Assessment Report');
    expect(report).toContain('## Executive Summary');
  });

  it('includes scan metadata table', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('| **Target** | https://api.example.com/v1/chat |');
    expect(report).toContain('| **Scan ID** | scan-test-001 |');
  });

  it('computes risk score as percentage vulnerable', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    // 3/5 = 60%
    expect(report).toContain('| **Risk Score** | 60.0% |');
  });

  it('generates risk assessment for critical vulnerabilities', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    // Has critical findings, should say CRITICAL
    expect(report).toContain('Overall Risk Level: CRITICAL');
    expect(report).toContain('Immediate remediation is required');
  });

  it('generates MODERATE risk assessment when no critical/high', () => {
    const findings = [
      makeFinding({
        probeId: 'GA-001',
        severity: Severity.Medium,
        verdict: Verdict.Vulnerable,
      }),
      makeFinding({
        probeId: 'GA-002',
        severity: Severity.Low,
        verdict: Verdict.Safe,
      }),
      makeFinding({
        probeId: 'GA-003',
        severity: Severity.Low,
        verdict: Verdict.Safe,
      }),
      makeFinding({
        probeId: 'GA-004',
        severity: Severity.Low,
        verdict: Verdict.Safe,
      }),
    ];
    const result = makeResult({ findings, summary: makeSummary(findings) });
    const report = generateExecutiveReport(result);

    expect(report).toContain('MODERATE');
  });

  it('includes severity breakdown table', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('### Severity Breakdown');
    expect(report).toContain('| **Critical** |');
    expect(report).toContain('| **High** |');
    expect(report).toContain('| **Total Vulnerable** |');
  });

  it('includes category breakdown', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('## Category Breakdown');
    expect(report).toContain('Goal Adherence');
    expect(report).toContain('Tool Safety');
  });

  it('includes confirmed vulnerabilities with PoC', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('## Confirmed Vulnerabilities');
    expect(report).toContain('### GA-001: Direct Instruction Override');
    expect(report).toContain('**Proof of Concept**');
  });

  it('includes inconclusive findings table', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('## Inconclusive Findings');
    expect(report).toContain('MI-001');
  });

  it('includes prioritized recommendations', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('## Recommendations');
    // Should have recommendations for Goal Adherence vulnerabilities
    expect(report).toContain('Harden system prompt boundaries');
  });

  it('handles zero vulnerabilities', () => {
    const findings = [
      makeFinding({ probeId: 'GA-001', verdict: Verdict.Safe }),
      makeFinding({ probeId: 'TS-001', verdict: Verdict.Safe }),
    ];
    const result = makeResult({ findings, summary: makeSummary(findings) });
    const report = generateExecutiveReport(result);

    expect(report).toContain('| **Risk Score** | 0.0% |');
    expect(report).toContain('robust security controls');
    expect(report).toContain('No confirmed vulnerabilities');
  });

  it('shows leakage signals in vulnerable findings', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('Leakage Signals Detected');
    expect(report).toContain('system_prompt_leak');
  });

  it('includes footer', () => {
    const result = makeResult();
    const report = generateExecutiveReport(result);

    expect(report).toContain('Report generated by Keelson');
  });
});
